### ISSUE TITLE
Enhance Github Actions

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-java-api#103]
In order to completely move from Travis-CI to github actions, following list of steps needs to be done.

- [ ] move bash files from `.travis` to `.github/scripts`
- [ ] add release action on tagging (based on contents of `travis.yml` file 
- [ ] test release process (add missing secrets)
- [ ] remove `travis.yml` file
- [ ] add publish to Sonar
- [ ] add publish test results (from matrix)

Part of wok is performed already as part of #102

**Comment by simasch** [comment]
Done
