### ISSUE TITLE
Align with output_buffer abstraction.

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-java-api#19]

**Comment by pesse** [comment]
Is this described in a different issue?

**Comment by viniciusam** [comment]
This refers to the feature/ut_output_buffer branch in the Java API:
https://github.com/utPLSQL/utPLSQL-java-api/tree/feature/output_buffer

and the feature/reporters_object_model_fix in the framework:
https://github.com/utPLSQL/utPLSQL/tree/feature/reporters_object_model_fix
https://github.com/utPLSQL/utPLSQL/issues/391

This is quite a big change and I think it needs a careful look. I'm not sure if it is a good thing to do at the moment.

**Comment by pesse** [comment]
This has already been fixed with 3.1.0
