### ISSUE TITLE
the call to `ut_runer.run` needs to have DBMS_OUTPUT enabled

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-java-api#20]
Currently it seems that some of the behaviours are not fully functional, if `dbms_output` is not enabled.
I see the odd behavior only in utPLSQL-cli (using java-api).

The end result is, that no calls to `dbms_output` are showing in ut_documentation_reporter` calls, while they should.

Interestingly I cannot reproduce this behavior in SQLDeveloper. It seems like a setting in JDBC driver, taht is ON by default in SQLDeveloper.

**Comment by viniciusam** [comment]
Can you explain a little bit more why the `dbms_output` is needed?

I think it's not possible to enable the `dbms_output` to show on the Java side during the procedure execution. What I can do is gather all output produced from `dbms_output` and show it at the end of the execution.

**Comment by jgebal** [comment]
To see the difference, run a test that does dbms_output.put_line.
Execute ut.run and see the output showin on documentation reporter.
Run the same with cli - output is not visible.
utPLSQL handles dbms_output buffer, but it needs to be enabled.
