### ISSUE TITLE
Timeout on long running tests

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-java-api#21]
If tests ron for a long time (20 minutes or so) the client disconnects.
Api should allow for long-running connections. The timeout could be a setting on client and connections should be closed gracefully if timeout occured.
We should use the timeout on buffer read to achieve this.
Maybe the buffer read (in utPLSQL) should throw exception on timeout.

**Comment by pesse** [comment]
Is this the same issue as https://github.com/utPLSQL/utPLSQL-cli/issues/20?

**Comment by pesse** [comment]
Fixed via #42
