### ISSUE TITLE
Jenkin not allows publish junit reports in Maven project

### ISSUE THREAD

**Issue by shrinathgurav** [utPLSQL/utPLSQL-java-api#41]
Hi,
I stuck with a problem as this project is a Maven project I am trying to integrate this API with jenkin. I am unable to publish xunit reports in Jenkins produced by utPLSQL. The xunit plugin is giving syntax format error while publishing results with xunit plugin. Junit plugin display the same results properly. The major issue is that junit plugin not work in Maven style projects and by creating free style project this project is not producing xml test results.  I am a databases developer and not know much about java, still trying to use this project for CI.

**Comment by shrinathgurav** [comment]
and by creating free style project this project is not producing xml test results. Hence I am a databases developer and not know much about java, still trying to use this project for CI.

**Comment by jgebal** [comment]
Hi @shrinathgurav 
The issue with xUnit plugin not being able to consume results from utPLSQL is related to xUnit plugin, not utPLSQL itself.

utPLSQL is producing report based on jUnit5 specification of test results.
According to this [junit4.xsd](https://gist.github.com/kuzuha/232902acab1344d6b578) element `<testsuite>` can be nested (see [line 58](https://gist.github.com/kuzuha/232902acab1344d6b578#file-junit4-xsd-L58) of the xsd).
utPLSQL is using nesting of suites and this is probably something not supported by xUnit plugin for Jenkins.
I would recommend raising an issue to the xUnit plugin, so they can fix this.
You may see the xUnit plugin issues related to `testsuite` [here](https://issues.jenkins-ci.org/browse/JENKINS-35407?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20xunit-plugin%20AND%20text%20~%20%22testsuite%22)

I don't know why you say you can't use [jUnit plugin](https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin) to publish results of a maven project in Jenkins.
There should be no issues with that so I would recommend using the **jUnit plugin for Jenkins** with utPLSQL.

**Comment by shrinathgurav** [comment]
@jgebal 
  Jenkins is not showing "publish junit test result" option for Maven project in post build action section. It is an existing issue with Jenkins  https://issues.jenkins-ci.org/browse/JENKINS-9980

**Comment by jgebal** [comment]
Seems like your only option is to go with the free-style project.
We can't really change the way ut_xunit_reporter is formatting outcomes as the outcomes represent suite-nesting.
