### ISSUE TITLE
Prevent JavaApiVersionInfo change on build

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL-java-api#58]
Let's move build number outside of `JavaApiVersionInfo` class so that it is not changed on build. Build number should be put into another file, like `MANIFEST.MD` or `utplsq-api.version`. Changing sources on compilation is never a good idea.

**Comment by pesse** [comment]
Any improvement on that is absolutely appreciated. Adding VersionInfo in the way it's done was just a quick-win compared to having no VersionInfo at all.
