### ISSUE TITLE
Introduce ParametersAreNonnullByDefault and mark nullable parameters as Nullable

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL-java-api#60]
Being a modern library we should mark our base package with `@ParametersAreNonnullByDefault` annotation and mark all nullable parameters as `@Nullable` within the code using JSR305.

**Comment by pesse** [comment]
Sure, go ahead 👍 
I didn't know there was such a thing. One of the issues of being 100% self-taught.
