### ISSUE TITLE
Different FileMapper call 3.0.0 to 3.0.2

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL-java-api#92]
The FileMapper has a different behaviour regarding parameters in versions 3.0.0 to 3.0.2:

3.0.2: https://github.com/utPLSQL/utPLSQL/blob/v3.0.2/source/core/ut_file_mapper.pkb#L69
3.0.3: https://github.com/utPLSQL/utPLSQL/blob/v3.0.3/source/core/ut_file_mapper.pkb#L75

So with the current calling, versions 3.0.0 to 3.0.2 will not get default TypeMapping when no explicit mapping is passed.

This can be solved by introducing a Compatiblity-Version of FileMapper similar to the one we have for TestRunnerStatement. For 3.0.0 to 3.0.2 we should not pass arguments that are NULL or empty (in respect of https://github.com/utPLSQL/utPLSQL-cli/issues/162).
From 3.0.3 on we can stay with the current approach of passing all parameters.

**Comment by jgebal** [comment]
There is different solution That I'd like to suggest.

Work without compatibility-version of FileMapper. 

You need to always use method of providing only the defined parameters and leave rest undefined (to not provide them to the PLSQL procedure call). That way, you always rely on default values for a given version.

This would be aligned with solution you had in mind for 3.0.0-3.0.2
This solution will apply to all versions released up till now.
We do not plan/envision any majo changes to file-mapper logic as it works perfectly as it is now.

**Comment by pesse** [comment]
Yes, this is a much better solution, thanks for bringing it up.
