### ISSUE TITLE
Maven repository doesn't work?

### ISSUE THREAD

**Issue by gdubya** [utPLSQL/utPLSQL-java-api#97]
Is the URL mentioned in the README correct?

https://packagecloud.io/utplsql/utplsql-java-api/maven2 does not seem to work

**Comment by pesse** [comment]
This URL is just the base-path for the Maven repository (which works fine for me). It is normal that the base URL of a Maven repo doesn't return anything.
Maven will expect several files to be existent based from the given artifact description. For version 3.1.7 for the API, for example, it will request
https://packagecloud.io/utplsql/utplsql-java-api/maven2/org/utplsql/java-api/3.1.7/java-api-3.1.7.pom (which works).

To see what JARs and versions are available, you can visit https://packagecloud.io/utPLSQL/utPLSQL-java-api

Does that solve your issue?

**Comment by gdubya** [comment]
Thanks for the fast response @pesse!

I'm trying to set up the repo as a mirror in Artifactory, but when i test the connection Artifactory returns 404, which is the same as i see in the browser so i assumed it was a problem. Perhaps it can be ignored then.

![image](https://user-images.githubusercontent.com/446033/74329221-aa3ce100-4d8f-11ea-9ef7-0f1b1f46037d.png

**Comment by gdubya** [comment]
Actually i was a bit too hasty. It appears as thought it does not work for Artifactory for some reason:
![image](https://user-images.githubusercontent.com/446033/74330036-3ef40e80-4d91-11ea-8bc4-c16d4fb163ff.png)

**Comment by gdubya** [comment]
Crosspost, since this seems more like an Artifactory / packagecloud issue than utplsql: https://stackoverflow.com/questions/60187305/how-to-configure-a-packagecloud-io-maven-repository-as-an-artifactory-mirror

I'll update this thread with an answer if / when i find it.

**Comment by simasch** [comment]
Using Maven Central instead
