### ISSUE TITLE
Getting Assertion Error "Fail to convert Internal Representation <TodaysDate>"

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL-java-api#99]
HI @Pazus ,

I am trying to use your UTPLSQ_JAVA_API code base for trying out  & executing the packages through Java API's.

I am trying to use "https://github.com/Pazus/utPLSQL-java-api.git" this project & did the required the changes for the DB connection details.

I am trying to run "/utPLSQL-java-api/src/test/java/io/github/utplsql/api/TestRunnerTest.java" which is throwing us a "Assertion Error "Fail to convert Internal Representation 2021-03-16"

Kindly please help us here to understand the issue more .

**Comment by simasch** [comment]
Hi @venkat-kasula Why are you trying to run this old project?

**Comment by jgebal** [comment]
Pazus repository is not official utPLSQL repository. 
Please use latest version of official sources.

**Comment by simasch** [comment]
This issue is not relevant because not based on the original source code
